- name: Refresh the APT package index and install required base packages
  ansible.builtin.apt:
    update_cache: true

- name: Install the base system packages required for Kubernetes setup
  ansible.builtin.apt:
    name: "{{ apt_packages | from_yaml }}"
    state: present
