---
- name: Install Kubernetes Addons
  hosts: localhost
  become: true

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - curl
        state: present

    - name: Install KubeCTX and KubeNS
      block:
        - name: Download kubectx
          ansible.builtin.get_url:
            url: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubectx
            dest: /usr/local/bin/kubectx
            mode: "0755"

        - name: Download kubens
          ansible.builtin.get_url:
            url: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubens
            dest: /usr/local/bin/kubens
            mode: "0755"

    - name: Install Helm
      block:
        - name: Create a temporary directory
          ansible.builtin.file:
            path: "/tmp/helm_temp"
            state: directory
            mode: "0777"

        - name: Download Helm
          ansible.builtin.get_url:
            url: "https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz"
            dest: "/tmp/helm_temp/helm.tar.gz"
            mode: "0777"

        - name: Extract Helm
          ansible.builtin.unarchive:
            src: "/tmp/helm_temp/helm.tar.gz"
            dest: "/tmp/helm_temp"

        - name: Copy Helm Binary to bin directory
          ansible.builtin.copy:
            src: "/tmp/helm_temp/linux-amd64/helm"
            dest: "/usr/local/bin/helm"
            remote_src: true
            owner: "{{ host_username.stdout }}"
            group: "{{ host_username.stdout }}"
            mode: "0644"

        - name: Clean up temporary directory
          ansible.builtin.file:
            path: "/tmp/helm_temp"
            state: absent

    - name: Install K9s
      block:
        - name: Download K9s
          ansible.builtin.get_url:
            url: "https://github.com/derailed/k9s/releases/download/v0.31.7/k9s_Linux_amd64.tar.gz"
            dest: "/tmp/k9s.tar.gz"
            mode: "0777"

        - name: Extract K9s
          ansible.builtin.unarchive:
            src: "/tmp/k9s.tar.gz"
            dest: "/usr/local/bin/"
            remote_src: true
            creates: "/usr/local/bin/k9s"

        - name: Set executable permissions
          ansible.builtin.file:
            path: "/usr/local/bin/k9s"
            mode: "0755"

        - name: Clean up temporary files
          ansible.builtin.file:
            path: "/tmp/k9s.tar.gz"
            state: absent
