---
- name: Install Kubernetes Addons
  hosts: localhost
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
        state: present

    - name: Install KubeCTX and KubeNS
      block:
        - name: Download kubectx
          get_url:
            url: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubectx
            dest: /usr/local/bin/kubectx
            mode: "0755"

        - name: Download kubens
          get_url:
            url: https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubens
            dest: /usr/local/bin/kubens
            mode: "0755"

    - name: Install Helm
      block:
        - name: Create a temporary directory
          ansible.builtin.file:
            path: "/tmp/helm_temp"
            state: directory

        - name: Download Helm
          ansible.builtin.get_url:
            url: "https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz"
            dest: "/tmp/helm_temp/helm.tar.gz"

        - name: Extract Helm
          ansible.builtin.unarchive:
            src: "/tmp/helm_temp/helm.tar.gz"
            dest: "/tmp/helm_temp"

        - name: Move Helm binary to /usr/local/bin
          ansible.builtin.command:
            cmd: "mv /tmp/helm_temp/linux-amd64/helm /usr/local/bin/"

        - name: Clean up temporary directory
          ansible.builtin.file:
            path: "/tmp/helm_temp"
            state: absent
