---
- name: Init Kubernetes
  hosts: localhost
  become: yes

  tasks:
    - name: get the username running the deploy
      become: false
      shell: "/bin/bash -c 'whoami'"
      register: host_username

    - name: Display Command Output
      debug:
        var: host_username.stdout

    ##################################################################################################################################

    - name: Run the command and capture output
      shell: "/bin/bash -c 'containerd config default > /etc/containerd/config.toml'"

    ##################################################################################################################################
    - name: Update containerD file
      shell: "sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml"

    ##################################################################################################################################
    - name: Run the command and capture output
      shell: "/bin/bash -c 'systemctl restart containerd'"

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: yes

    - name: Copy kubeconfig to user's home directory
      copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "/home/{{ host_username.stdout }}/.kube/config"
        remote_src: yes
        owner: "{{ host_username.stdout }}"
        group: "{{ host_username.stdout }}"
        mode: "0644"

