- name: Install Apt Packages
  ansible.builtin.include_tasks: install_apt_packages.yaml

- name: Configure ContainerD
  ansible.builtin.include_tasks: configure_containerd.yaml

- name: Configure modProbe
  ansible.builtin.include_tasks: configure_modprobe.yaml

- name: Init Cluster
  ansible.builtin.include_tasks: init_cluster.yaml
