- name: Apply cert-manager manifest
  ansible.builtin.shell: |
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml
  register: cert_manager_result
  changed_when: "'created' in cert_manager_result.stdout or 'configured' in cert_manager_result.stdout"
  failed_when: cert_manager_result.rc != 0

- name: Add actions-runner-controller Helm repository
  ansible.builtin.shell: |
    helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
  register: helm_repo_result
  changed_when: "'actions-runner-controller' in helm_repo_result.stdout"
  failed_when: helm_repo_result.rc != 0

- name: Install or upgrade actions-runner-controller Helm chart
  ansible.builtin.shell: |
    helm upgrade --install --namespace actions-runner-system --create-namespace \
      --set=authSecret.create=true \
      --set=authSecret.github_token="{{ github_token }}" \
      -f template/values.yaml \
      --wait actions-runner-controller actions-runner-controller/actions-runner-controller
  register: helm_install_result
  changed_when: "'deployed' in helm_install_result.stdout or 'upgraded' in helm_install_result.stdout"
  failed_when: helm_install_result.rc != 0