- name: Remove control-plane taint from the current node
  ansible.builtin.shell: |
    kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane-
  register: taint_result
  changed_when: "'node-role.kubernetes.io/control-plane-' in taint_result.stdout or taint_result.stderr"
  failed_when: taint_result.rc != 0
  ignore_errors: true


- name: Load br_netfilter kernel module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter module is loaded on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/br_netfilter.conf
    content: "br_netfilter\n"
    owner: root
    group: root
    mode: '0644'

- name: Configure Kubernetes networking sysctl parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
  changed_when: true

