- name: Configure ContainerD
  block:
    - name: Generate ContainerD file
      register: generate_containerd
      changed_when: generate_containerd.rc != 0
      ansible.builtin.shell: |
        containerd config default > /etc/containerd/config.toml
      args:
        executable: /bin/bash

    - name: Update ContainerD file
      register: sed_containerd
      changed_when: sed_containerd.rc != 0
      ansible.builtin.shell: |
        sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
      args:
        executable: /bin/bash

    - name: Start containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true

- name: Fix swap
  block:
    - name: Disable swap for current session
      register: disable_swap
      changed_when: disable_swap.rc != 0
      ansible.builtin.shell: |
        swapoff -a
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Disable swap permanently, persist reboots
      replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: true

- name: Init K8s Kluster
  block:
    - name: Initialize Kubernetes
      register: kubernetes_init
      changed_when: kubernetes_init.rc != 0
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr={{ k8s_pod_cidr }}
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Create
      ansible.builtin.file:
        path: "/home/{{ ansible_env.SUDO_USER }}/.kube/"
        state: directory
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0755"

    - name: Copy kubeconfig to user's home directory
      ansible.builtin.copy:
        src: "/etc/kubernetes/admin.conf"
        dest: "/home/{{ ansible_env.SUDO_USER }}/.kube/config"
        remote_src: true
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0755"

    - name: Install Flannel as the pod network add-on
      register: kubernetwork
      become: false
      changed_when: kubernetwork.rc != 0
      ansible.builtin.shell: |
        kubectl apply -f {{ k8s_flannel_url }}
      args:
        executable: /bin/bash
