configs:
  secret:
    argocdServerAdminPassword: "$2y$10$IsjzEJkHKt9AoUHfmzp/9uae34AUXR/YAxyyc7Kk8StWJmZa3U6US" # admin

server:
  service:
    type: NodePort
    nodePortHttp: 32080
    nodePortHttps: 32443
    ports:
      http: 80
      https: 443
