configs:
  secret:
    argocdServerAdminPassword: "$2a$10$sjU6Yoii/IOaVsRdJXBq9e3Kgfjd9UcyTK/G3AhuXW5PmPn0xKTHy" # admin

controller:
  clusterAdminAccess: true

server:
  service:
    type: NodePort
    nodePortHttp: 30000
    nodePortHttps: 30001
    ports:
      http: 80
      https: 443
