apiVersion: v1
kind: PersistentVolume
metadata:
  name: dind-cache-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # only works on single-node setups (use NFS, EBS, etc. for multi-node)
    path: /mnt/data/dind-cache
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-cache-pvc
  namespace: actions-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: dind-cache-pv # bind to the specific PV above
