apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: praiacarioca
spec:
  replicas: 1
  template:
   spec:
     # https://github.com/actions/actions-runner-controller/blob/master/docs/deploying-alternative-runners.md
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      repository: rhattox-javascript/praiaCarioca
      dockerMTU: 1450
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"