  # Initialize Kubernetes Cluster and Configure Networking
- name: Initialize Kubernetes Cluster
  block:
    - name: Run kubeadm init
      register: kubernetes_init
      changed_when: kubernetes_init.rc != 0
      ansible.builtin.shell: |
        kubeadm init --pod-network-cidr={{ k8s_pod_cidr }}
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Create .kube Directory for User
      ansible.builtin.file:
        path: "/home/{{ ansible_env.SUDO_USER }}/.kube/"
        state: directory
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0750"

    - name: Copy Kubeconfig to User Home Directory
      ansible.builtin.copy:
        src: "{{ kube_config_default_path }}"
        dest: "{{ user_config_default_path }}"
        remote_src: true
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0750"

    - name: Create .kube Directory for Root
      ansible.builtin.file:
        path: "/root/.kube/"
        state: directory
        owner: "root"
        group: "root"
        mode: "0750"

    - name: Copy Kubeconfig to Root Home Directory
      ansible.builtin.copy:
        src: "{{ kube_config_default_path }}"
        dest: "/root/.kube/config"
        remote_src: true
        owner: "root"
        group: "root"
        mode: "0750"

    - name: Install Flannel Pod Network Add-on
      register: kubernetwork
      become: false
      changed_when: kubernetwork.rc != 0
      ansible.builtin.shell: |
        kubectl apply -f {{ k8s_flannel_url }}
      args:
        executable: /bin/bash

    - name: Remove Control-Plane Taint from Current Node
      ansible.builtin.shell: |
        kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/control-plane-
      register: taint_result
      changed_when: "'node-role.kubernetes.io/control-plane-' in taint_result.stdout or taint_result.stderr"
      failed_when: taint_result.rc != 0
      ignore_errors: true
