# Configure ContainerD with SystemdCgroup Support
- name: Configure ContainerD with SystemdCgroup Support
  block:
    - name: Check and Prepare ContainerD Configuration File
      block:
        - name: Check if ContainerD Config File Exists
          ansible.builtin.stat:
            path: "{{ containerd_file_path }}"
          register: file_check

        - name: Remove Existing ContainerD Config File if Present
          when: file_check.stat.exists
          ansible.builtin.file:
            path: "{{ containerd_file_path }}"
            state: absent

    - name: Verify ContainerD Config File Status
      ansible.builtin.stat:
        path: "{{ containerd_file_path }}"
      register: file_check

    - name: Create ContainerD Configuration Directory
      ansible.builtin.file:
        path: "/etc/containerd"
        state: directory
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0750"

    - name: Generate Default ContainerD Configuration File
      register: generate_containerd
      changed_when: generate_containerd.rc != 0
      ansible.builtin.shell: |
        containerd config default > /etc/containerd/config.toml
      args:
        executable: /bin/bash

    - name: Enable SystemdCgroup in ContainerD Configuration
      ansible.builtin.lineinfile:
        path: "{{ containerd_file_path }}"
        regexp: '^(\s*)SystemdCgroup = false'
        line: "SystemdCgroup = true"
        backup: true
      register: lineinfile_result
      changed_when: lineinfile_result.changed

    - name: Restart and Enable ContainerD Service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true
