- name: Check if the GPG Key exists
  ansible.builtin.stat:
    path: "{{ key_location }}"
  register: file_check

- name: Remove GPG file
  when: file_check.stat.exists
  ansible.builtin.file:
    path: "{{ key_location }}"
    state: absent

- name: Check if the GPG Key exists
  ansible.builtin.stat:
    path: "{{ key_location }}"
  register: file_check

- name: Download And Install GPG Key
  block:
    - name: Download GPG Key
      when: not file_check.stat.exists
      ansible.builtin.get_url:
        url: "{{ gpg_key_url }}"
        dest: "{{ tmp_key_location }}"
        mode: "0644"

    - name: Install GPG Key
      changed_when: false
      when: not file_check.stat.exists
      ansible.builtin.shell: |
        cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
      args:
        executable: /bin/bash

    - name: Remove tmp file
      when: not file_check.stat.exists
      ansible.builtin.file:
        path: "{{ tmp_key_location }}"
        state: absent

    - name: Update APT package cache
      when: not file_check.stat.exists
      ansible.builtin.apt:
        update_cache: true

    - name: Install APT repository
      when: not file_check.stat.exists
      ansible.builtin.apt_repository:
        repo: "{{ apt_url }}"
        state: present
        filename: "{{ app_name }}"
