- name: Install KubeCTX and KubeNS
  block:
    - name: Download kubectx
      ansible.builtin.get_url:
        url: "{{ kubectx_url }}/kubectx"
        dest: "{{ install_path }}/kubectx"
        mode: "0550"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Download kubens
      ansible.builtin.get_url:
        url: "{{ kubectx_url }}/kubens"
        dest: "{{ install_path }}/kubens"
        mode: "0550"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

- name: Install Helm
  block:
    - name: Create a temporary directory
      ansible.builtin.file:
        path: "/tmp/helm_temp"
        state: directory
        mode: "0777"

    - name: Download Helm
      ansible.builtin.get_url:
        url: "{{ helm_url }}"
        dest: "/tmp/helm_temp/helm.tar.gz"
        mode: "0777"

    - name: Extract Helm
      ansible.builtin.unarchive:
        src: "/tmp/helm_temp/helm.tar.gz"
        dest: "/tmp/helm_temp"

    - name: Copy Helm Binary to bin directory
      ansible.builtin.copy:
        src: "/tmp/helm_temp/linux-amd64/helm"
        dest: "{{ install_path }}/helm"
        remote_src: true
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0550"

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "/tmp/helm_temp"
        state: absent

- name: Install NerdCTL
  block:
    - name: Create a temporary directory
      ansible.builtin.file:
        path: "/tmp/nerdctl_tmp"
        state: directory
        mode: "0777"

    - name: Download NerdCTL
      ansible.builtin.get_url:
        url: "{{ nerdctl_url }}"
        dest: "/tmp/nerdctl_tmp/nerdctl.tar.gz"
        mode: "0777"

    - name: Extract NerdCTL
      ansible.builtin.unarchive:
        src: "/tmp/nerdctl_tmp/nerdctl.tar.gz"
        dest: "/tmp/nerdctl_tmp"

    - name: Copy containerd-rootless and bin files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/"
        mode: "0550"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        remote_src: true
      with_fileglob:
        - "/tmp/nerdctl_tmp/containerd-rootless*"
        - "/tmp/nerdctl_tmp/bin/*"


    - name: install rootless setup for nerdctl
      become: false
      ansible.builtin.command: /tmp/nerdctl_tmp/bin/containerd-rootless-setuptool.sh install
      changed_when: true

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "/tmp/nerdctl_tmp"
        state: absent
