- name: Update Packages And Add Required Packages
  block:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Prerequisites
      ansible.builtin.apt:
        name: "{{ apt_packages | from_yaml }}"
        state: present
