# Update and Install Basic APT Packages
- name: Update APT Cache and Install Basic Packages
  block:
    - name: Update APT Package Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Basic Prerequisite Packages
      ansible.builtin.apt:
        name: "{{ apt_packages | from_yaml }}"
        state: present
