# Install KubeCTX, KubeNS, and Helm
- name: Install KubeCTX and KubeNS Utilities
  block:
    - name: Download kubectx Utility
      ansible.builtin.get_url:
        url: "{{ kubectx_url }}/kubectx"
        dest: "{{ install_path }}/kubectx"
        mode: "0550"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Download kubens Utility
      ansible.builtin.get_url:
        url: "{{ kubectx_url }}/kubens"
        dest: "{{ install_path }}/kubens"
        mode: "0550"
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

- name: Install Helm Utility
  block:
    - name: Create Temporary Directory for Helm
      ansible.builtin.file:
        path: "/tmp/helm_temp"
        state: directory
        mode: "0777"

    - name: Download Helm Archive
      ansible.builtin.get_url:
        url: "{{ helm_url }}"
        dest: "/tmp/helm_temp/helm.tar.gz"
        mode: "0777"

    - name: Extract Helm Archive
      ansible.builtin.unarchive:
        src: "/tmp/helm_temp/helm.tar.gz"
        dest: "/tmp/helm_temp"

    - name: Copy Helm Binary to Installation Directory
      ansible.builtin.copy:
        src: "/tmp/helm_temp/linux-amd64/helm"
        dest: "{{ install_path }}/helm"
        remote_src: true
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        mode: "0550"

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: "/tmp/helm_temp"
        state: absent
