- name: Configure kernel modules and sysctl for Kubernetes
  block:
    - name: Ensure br_netfilter module is loaded
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Ensure br_netfilter loads on boot
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/br_netfilter.conf
        line: br_netfilter
        create: true
        owner: root
        group: root
        mode: "0644"

    - name: Write Kubernetes sysctl parameters
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
        owner: root
        group: root
        mode: "0644"

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system
      changed_when: true
