# Manage GPG Key for APT Repository
- name: Check if GPG Key Exists
  ansible.builtin.stat:
    path: "{{ key_location }}"
  register: file_check

  # Remove GPG Key File if Present
- name: Remove GPG Key File if Present
  when: file_check.stat.exists
  ansible.builtin.file:
    path: "{{ key_location }}"
    state: absent

- name: Check if GPG Key Exists (Recheck)
  ansible.builtin.stat:
    path: "{{ key_location }}"
  register: file_check

  # Download and Install GPG Key
- name: Download and Install GPG Key
  block:
    - name: Download GPG Key File
      when: not file_check.stat.exists
      ansible.builtin.get_url:
        url: "{{ gpg_key_url }}"
        dest: "{{ tmp_key_location }}"
        mode: "0644"

    - name: Install GPG Key to System
      changed_when: false
      when: not file_check.stat.exists
      ansible.builtin.shell: |
        cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
      args:
        executable: /bin/bash

    - name: Remove Temporary GPG Key File
      when: not file_check.stat.exists
      ansible.builtin.file:
        path: "{{ tmp_key_location }}"
        state: absent

    - name: Update APT Package Cache After GPG Key Install
      when: not file_check.stat.exists
      ansible.builtin.apt:
        update_cache: true

    - name: Add APT Repository
      when: not file_check.stat.exists
      ansible.builtin.apt_repository:
        repo: "{{ apt_url }}"
        state: present
        filename: "{{ app_name }}"
